// Central data store for DEEYORA — Digital Growth Agency

export const services = [
  {
    id: "social-media-marketing",
    number: "01",
    name: "Social Media",
    slug: "social-media-marketing",
    description: "Build attention. Grow your audience.",
    capabilities: ["Platform Strategy", "Content Planning", "Community Mgmt", "Reels & Stories"],
    icon: "📱",
  },
  {
    id: "seo",
    number: "02",
    name: "SEO",
    slug: "seo",
    description: "Get found by the right people.",
    capabilities: ["Technical SEO", "Keyword Strategy", "Content Optimization", "Performance Tracking"],
    icon: "🔍",
  },
  {
    id: "performance-marketing",
    number: "03",
    name: "Performance Marketing",
    slug: "performance-marketing",
    description: "Turn ad spend into results.",
    capabilities: ["Campaign Strategy", "Audience Research", "Creative Testing", "ROAS Tracking"],
    icon: "📈",
  },
  {
    id: "google-ads",
    number: "04",
    name: "Google Ads",
    slug: "google-ads",
    description: "Reach customers ready to act.",
    capabilities: ["Search Campaigns", "Display Ads", "Shopping Ads", "Remarketing"],
    icon: "🎯",
  },
  {
    id: "meta-ads",
    number: "05",
    name: "Meta Ads",
    slug: "meta-ads",
    description: "Reach the right audience at scale.",
    capabilities: ["Audience Targeting", "Creative Strategy", "A/B Testing", "Conversion Scale"],
    icon: "⚡",
  },
  {
    id: "content-marketing",
    number: "06",
    name: "Content",
    slug: "content-marketing",
    description: "Create content people care about.",
    capabilities: ["Content Strategy", "Article Writing", "Video Scripting", "Distribution"],
    icon: "✍️",
  },
  {
    id: "brand-strategy",
    number: "07",
    name: "Brand Strategy",
    slug: "brand-strategy",
    description: "Build a brand people remember.",
    capabilities: ["Brand Positioning", "Visual Identity", "Brand Voice", "Core Messaging"],
    icon: "🎨",
  },
  {
    id: "website-design",
    number: "08",
    name: "Web Design & Development",
    slug: "website-design",
    description: "Turn visitors into customers.",
    capabilities: ["UX/UI Design", "Web Development", "Landing Pages", "Speed & Conversion"],
    icon: "💻",
  },
  {
    id: "ai-marketing",
    number: "09",
    name: "AI Marketing",
    slug: "ai-marketing",
    description: "Work smarter with AI.",
    capabilities: ["AI Research", "Marketing Automation", "AI Analytics", "Campaign Tuning"],
    icon: "🤖",
  },
];

export const growthStages = [
  {
    id: "brand",
    number: "01",
    label: "Brand",
    emoji: "🎯",
    goal: "Build a clear, memorable identity.",
    whatWeDo: "Brand Strategy + Visual Identity + Messaging",
    outcome: "A recognized brand built to convert.",
    tools: ["Brand Strategy", "Positioning", "Visual Identity"],
  },
  {
    id: "content",
    number: "02",
    label: "Content",
    emoji: "✍️",
    goal: "Attract and build trust.",
    whatWeDo: "Content Strategy + SEO Articles + Social Media",
    outcome: "Organic reach and domain authority.",
    tools: ["Content Strategy", "SEO Content", "Social Media"],
  },
  {
    id: "traffic",
    number: "03",
    label: "Traffic",
    emoji: "📈",
    goal: "Reach the right audience.",
    whatWeDo: "SEO + Google Ads + Meta Ads",
    outcome: "More qualified visitors on high-intent pages.",
    tools: ["Google Ads", "Meta Ads", "SEO"],
  },
  {
    id: "leads",
    number: "04",
    label: "Leads",
    emoji: "📋",
    goal: "Turn visitors into interested prospects.",
    whatWeDo: "Landing Pages + Offer Strategy + Lead Magnets",
    outcome: "Predictable pipeline of qualified leads.",
    tools: ["Landing Pages", "Lead Magnets", "CRM"],
  },
  {
    id: "sales",
    number: "05",
    label: "Sales",
    emoji: "💰",
    goal: "Convert prospects into paying customers.",
    whatWeDo: "Funnel Optimization + Email Nurture + Retargeting",
    outcome: "Higher sales conversion rate and faster sales cycles.",
    tools: ["Sales Funnel", "Email Sequences", "Retargeting"],
  },
  {
    id: "growth",
    number: "06",
    label: "Growth",
    emoji: "🚀",
    goal: "Scale what works and optimize.",
    whatWeDo: "AI Optimization + Automation + Advanced Analytics",
    outcome: "Compounding revenue growth with lower CAC.",
    tools: ["Analytics", "AI Optimization", "Automation"],
  },
];

export const whyDeeyoraCards = [
  {
    id: "strategy",
    number: "01",
    title: "Strategy First",
    body: "Start with the business goal.",
    detail: "Every action connects back to revenue and clear metrics.",
    icon: "🎯",
  },
  {
    id: "creative",
    number: "02",
    title: "Creative That Works",
    body: "Ideas that drive action.",
    detail: "Compelling storytelling designed for maximum response.",
    icon: "✨",
  },
  {
    id: "data",
    number: "03",
    title: "Data Over Guesswork",
    body: "Measure. Learn. Improve.",
    detail: "Relentless iteration based on actual performance data.",
    icon: "📊",
  },
  {
    id: "ai",
    number: "04",
    title: "AI When It Helps",
    body: "Work faster and smarter.",
    detail: "Modern technology to automate research and scale output.",
    icon: "🤖",
  },
];

export const aiWorkflowSteps = [
  {
    step: "01",
    name: "Research",
    desc: "AI-assisted market research & intent analysis.",
    icon: "🔍",
  },
  {
    step: "02",
    name: "Create",
    desc: "Rapid creative iteration & copy variant generation.",
    icon: "🎨",
  },
  {
    step: "03",
    name: "Test",
    desc: "Automated multivariate campaign & ad testing.",
    icon: "⚡",
  },
  {
    step: "04",
    name: "Optimize",
    desc: "Continuous bid tuning & budget allocation.",
    icon: "📈",
  },
];

export const caseStudies = [
  {
    id: "local-business-growth",
    number: "01",
    title: "Local Business Scale",
    category: "Growth Concept",
    tags: ["Local SEO", "Google Ads", "Reviews"],
    challenge: "A local service business with zero digital presence.",
    strategy: "Google Business setup, local SEO & targeted search ads.",
    outcome: "2× lead inquiries within 90 days (Illustrative concept).",
  },
  {
    id: "d2c-brand-launch",
    number: "02",
    title: "D2C Brand Activation",
    category: "Brand Project",
    tags: ["Brand Strategy", "Meta Ads", "Creative"],
    challenge: "New product launching in a crowded niche.",
    strategy: "Story-led Meta ads paired with high-converting landing page.",
    outcome: "Break-even ROAS achieved in 60 days (Illustrative concept).",
  },
  {
    id: "creator-growth-strategy",
    number: "03",
    title: "Creator Engine",
    category: "Campaign Experiment",
    tags: ["Social Media", "Content", "SEO"],
    challenge: "Stagnant organic traffic and low audience engagement.",
    strategy: "Content distribution engine & search-optimized articles.",
    outcome: "3× organic reach expansion (Illustrative concept).",
  },
];

export const blogPosts = [
  {
    id: "strategy-before-content",
    title: "Strategy Before Content — Always",
    category: "Marketing",
    readTime: "5 min read",
    date: "Aug 2026",
    excerpt: "Most brands start creating before they know what they want people to do. Here's why that's backwards.",
    slug: "strategy-before-content",
  },
  {
    id: "seo-in-ai-age",
    title: "SEO in the AI Age: What Actually Changed",
    category: "SEO",
    readTime: "7 min read",
    date: "Aug 2026",
    excerpt: "AI search changed how people find things. But the fundamentals of good SEO got more important, not less.",
    slug: "seo-in-ai-age",
  },
  {
    id: "meta-ads-creative-testing",
    title: "How to Test Meta Ad Creatives (The Right Way)",
    category: "Performance",
    readTime: "6 min read",
    date: "Jul 2026",
    excerpt: "Most brands test ads wrong and waste budget. Here's a structured approach that actually tells you something.",
    slug: "meta-ads-creative-testing",
  },
];

export const industries = [
  {
    name: "E-commerce",
    label: "What works",
    strategies: ["Meta Ads", "SEO", "Retargeting", "UGC"],
  },
  {
    name: "Local Business",
    label: "What works",
    strategies: ["Google Business", "Local SEO", "Google Search Ads", "Reviews"],
  },
  {
    name: "Restaurants",
    label: "What works",
    strategies: ["Local SEO", "Social Reels", "Google Business", "Review Engine"],
  },
  {
    name: "Real Estate",
    label: "What works",
    strategies: ["Lead Gen Ads", "Google Search Ads", "Video Tours", "CRM Automation"],
  },
  {
    name: "Startups",
    label: "What works",
    strategies: ["Brand Strategy", "Performance Ads", "Growth Experiments", "SEO"],
  },
  {
    name: "Education",
    label: "What works",
    strategies: ["Meta Ads", "YouTube SEO", "Email Nurturing", "Remarketing"],
  },
  {
    name: "Professional Services",
    label: "What works",
    strategies: ["LinkedIn Ads", "Content Authority", "Google Search", "Lead Nurture"],
  },
  {
    name: "Personal Brands",
    label: "What works",
    strategies: ["Brand Positioning", "Content Strategy", "Social Growth", "Newsletter"],
  },
];

export const pricingPlans = [
  {
    id: "starter",
    name: "STARTER",
    tagline: "Build your digital foundation.",
    bestFor: "New businesses getting started online.",
    features: [
      "Social media management (1 platform)",
      "Monthly content calendar",
      "Basic SEO setup",
      "Monthly performance report",
      "Email support",
    ],
    cta: "Get a Custom Quote",
    highlighted: false,
  },
  {
    id: "growth",
    name: "GROWTH",
    tagline: "Build a consistent growth engine.",
    bestFor: "Businesses ready for more leads and sales.",
    features: [
      "Social media (2–3 platforms)",
      "Content creation & strategy",
      "SEO (on-page + technical)",
      "Google or Meta Ads management",
      "Monthly strategy call",
      "Bi-weekly performance reports",
      "Dedicated account manager",
    ],
    cta: "Get a Custom Quote",
    highlighted: true,
  },
  {
    id: "scale",
    name: "SCALE",
    tagline: "Scale with advanced marketing.",
    bestFor: "Brands ready for multi-channel growth.",
    features: [
      "Full-funnel marketing strategy",
      "Multi-platform ad management",
      "Advanced SEO & content engine",
      "AI-powered optimization",
      "Weekly strategy calls",
      "CRO & landing page optimization",
      "Marketing automation setup",
      "Priority support",
    ],
    cta: "Get a Custom Quote",
    highlighted: false,
  },
];
